import streamlit as st
import time
import json
import sys
import asyncio
import queue
import threading
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from src.agent import Agent
from src.memory import ConversationMemory
from src.session_store import SessionStore
from src.multi_agent import MultiAgent
from src.user_store import register, login, get_profile, update_profile, get_user_context
from src.vector_store import upload_and_index, list_indexed_docs, add_document, add_session_memory, list_session_docs
from src.cost_tracker import get_user_usage, get_session_usage, format_cost, format_tokens

# ---------------------------------------------------------------------------
# Page config
# ---------------------------------------------------------------------------
st.set_page_config(page_title="Auto Research", page_icon=None, layout="wide")

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def run_async_in_thread(coro):
    """Run an async coroutine in a background thread and return events via queue."""
    event_queue = queue.Queue()
    exception_holder = [None]

    def _worker():
        try:
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)

            async def _consume():
                try:
                    async for event in coro:
                        event_queue.put(event)
                except Exception as e:
                    exception_holder[0] = e
                finally:
                    event_queue.put(None)  # sentinel

            loop.run_until_complete(_consume())
            loop.close()
        except Exception as e:
            exception_holder[0] = e
            event_queue.put(None)

    thread = threading.Thread(target=_worker, daemon=True)
    thread.start()
    return event_queue, thread, exception_holder


def build_markdown(result: dict, goal: str = "") -> str:
    md = "# Research Report\n\n"
    if goal:
        md += f"**Goal:** {goal}\n\n"
    md += f"**Status:** {'Success' if result.get('success') else 'Failed'}\n\n"
    md += f"**Steps:** {result.get('steps', 0)} | **Time:** {result.get('time', 0)}s\n\n"
    md += "---\n\n"
    md += f"## Result\n\n{result.get('final_answer', '')}\n\n"
    log = result.get("log", [])
    if log:
        md += "## Process Log\n\n"
        for step in log:
            tool = step.get("tool")
            md += f"### Step {step.get('step', '?')}"
            if tool:
                md += f" -- {tool}"
            md += "\n\n"
            if step.get("input"):
                md += f"**Input:**\n```json\n{json.dumps(step['input'], indent=2)}\n```\n\n"
            if step.get("output"):
                md += f"**Output:**\n```\n{step['output'][:1000]}\n```\n\n"
    md += "---\n\n*Generated by Auto Research*\n"
    return md


def build_pdf(result: dict, goal: str = "") -> bytes:
    try:
        import markdown as md_lib
        from weasyprint import HTML
        md = build_markdown(result, goal)
        html_content = md_lib.markdown(md, extensions=["tables", "fenced_code"])
        full_html = f"""<!DOCTYPE html>
<html><head><style>
  body {{ font-family: sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; color: #333; }}
  pre {{ background: #f4f4f4; padding: 12px; border-radius: 6px; overflow-x: auto; }}
  code {{ background: #f4f4f4; padding: 2px 4px; border-radius: 3px; }}
  h1 {{ border-bottom: 2px solid #333; padding-bottom: 8px; }}
</style></head><body>{html_content}</body></html>"""
        return HTML(string=full_html).write_pdf()
    except Exception:
        return b""


def render_result(result: dict, key_prefix: str = ""):
    status = "success" if result.get("success") else "failed"
    st.caption(
        f"Status: {status} | Steps: {result.get('steps', 0)} | "
        f"Time: {result.get('time', 0)}s"
    )
    log = result.get("log", [])
    if log:
        with st.expander(f"{len(log)} steps", expanded=False):
            for step in log:
                tool = step.get("tool")
                st.markdown(
                    f"**Step {step.get('step', '?')}**"
                    + (f" -- {tool}" if tool else " -- thinking")
                )
                if step.get("input"):
                    st.code(json.dumps(step["input"], indent=2), language="json")
                if step.get("output"):
                    st.text(step["output"][:500])
    sid = st.session_state.get("session_id")
    if sid:
        col1, col2, _ = st.columns([1, 1, 4])
        goal = ""
        for msg in reversed(st.session_state.sessions.get(sid, {}).get("messages", [])):
            if msg["role"] == "user":
                goal = msg["content"]
                break
        with col1:
            st.download_button(
                "Markdown",
                data=build_markdown(result, goal),
                file_name=f"report-{sid[:8]}.md",
                mime="text/markdown",
                key=f"{key_prefix}md_{sid}",
            )
        with col2:
            st.download_button(
                "PDF",
                data=build_pdf(result, goal),
                file_name=f"report-{sid[:8]}.pdf",
                mime="application/pdf",
                key=f"{key_prefix}pdf_{sid}",
            )


# ---------------------------------------------------------------------------
# Session state init
# ---------------------------------------------------------------------------
if "logged_in" not in st.session_state:
    st.session_state.logged_in = False
    st.session_state.username = ""

# Per-session chat histories: {session_id: {"messages": [...], "agent": ..., "memory": ...}}
if "sessions" not in st.session_state:
    st.session_state.sessions = {}

if "session_id" not in st.session_state:
    st.session_state.session_id = None

if "active_agent" not in st.session_state:
    st.session_state.active_agent = None

if "active_memory" not in st.session_state:
    st.session_state.active_memory = None

# Track uploaded files per session
if "session_uploads" not in st.session_state:
    st.session_state.session_uploads = {}

# Extracted text of uploaded files per session, for chat context injection
if "session_docs" not in st.session_state:
    st.session_state.session_docs = {}

store = SessionStore()

# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------
if not st.session_state.logged_in:
    st.title("Auto Research")
    tab_login, tab_register = st.tabs(["Login", "Register"])

    with tab_login:
        with st.form("login_form"):
            username = st.text_input("Username", key="login_user")
            password = st.text_input("Password", type="password", key="login_pass")
            submitted = st.form_submit_button("Login")
            if submitted:
                if not username or not password:
                    st.error("Enter username and password")
                elif login(username, password):
                    st.session_state.logged_in = True
                    st.session_state.username = username
                    st.rerun()
                else:
                    st.error("Invalid credentials")

    with tab_register:
        with st.form("register_form"):
            username = st.text_input("Username", key="reg_user")
            password = st.text_input("Password", type="password", key="reg_pass")
            submitted = st.form_submit_button("Register")
            if submitted:
                if not username or not password:
                    st.error("Enter username and password")
                elif len(password) < 4:
                    st.error("Password must be at least 4 characters")
                elif register(username, password):
                    st.session_state.logged_in = True
                    st.session_state.username = username
                    st.rerun()
                else:
                    st.error("Username already exists")

    st.stop()

# ---------------------------------------------------------------------------
# Sidebar
# ---------------------------------------------------------------------------
with st.sidebar:
    st.header("Auto Research")
    st.caption(f"Logged in as {st.session_state.username}")

    if st.button("New Chat", use_container_width=True):
        st.session_state.session_id = None
        st.session_state.active_agent = None
        st.session_state.active_memory = None
        st.rerun()

    st.divider()

    # --- Research Templates ---
    with st.expander("Research Templates", expanded=False):
        templates = {
            "Market Analysis": "Research the current market size, key players, trends, and growth forecast for [TOPIC]. Provide a structured analysis with data points.",
            "News Digest": "Find the latest 5 news articles about [TOPIC] from the past week. Sumimize each article in 2-3 sentences with source URLs.",
            "Competitor Research": "Research [COMPANY] and its top 3 competitors. Compare their products, pricing, market position, and recent news.",
            "Technical Deep Dive": "Explain [TECHNOLOGY] in detail: how it works, its architecture, use cases, pros/cons, and how it compares to alternatives.",
            "Event Summary": "Research [EVENT/CONFERENCE]. What were the key announcements, speakers, takeaways, and community reactions?",
        }
        for name, prompt in templates.items():
            if st.button(name, key=f"tpl_{name}", use_container_width=True):
                st.session_state["pending_template"] = prompt
                st.rerun()

    # --- Indexed docs overview ---
    with st.expander("Knowledge Base", expanded=False):
        docs = list_indexed_docs()
        if docs:
            st.caption(f"{len(docs)} shared docs")
            for d in docs:
                st.text(f"  {d['title']} ({d['chunks']} chunks)")
        else:
            st.caption("No shared documents")

        sid = st.session_state.get("session_id")
        if sid:
            sdocs = list_session_docs(sid)
            if sdocs:
                st.caption(f"{len(sdocs)} session memories")
                for d in sdocs:
                    st.text(f"  {d['goal'][:40]} ({d['chunks']} chunks)")

    st.divider()

    model = st.selectbox(
        "Model",
        ["deepseek-v4-flash", "deepseek-v4-pro"],
        index=0,
    )
    mode = st.radio(
        "Agent Mode",
        ["Single Agent", "Multi-Agent"],
        horizontal=True,
    )

    st.divider()

    # --- Usage Stats ---
    user_usage = get_user_usage(st.session_state.username)
    if user_usage.get("total_requests", 0) > 0:
        with st.expander("Usage Stats", expanded=False):
            st.caption(f"Total cost: {format_cost(user_usage['total_cost'])}")
            st.caption(f"Tokens: {format_tokens(user_usage['total_input_tokens'])} in / {format_tokens(user_usage['total_output_tokens'])} out")
            st.caption(f"Requests: {user_usage['total_requests']} | Sessions: {user_usage['sessions']}")

    st.subheader("Past Sessions")

    # Tag filter
    all_tags = store.get_all_tags(user=st.session_state.username)
    if all_tags:
        selected_tag = st.selectbox("Filter by tag", ["All"] + all_tags, key="tag_filter")
        if selected_tag == "All":
            selected_tag = ""
    else:
        selected_tag = ""

    sessions = store.list_sessions(limit=20, user=st.session_state.username, tag=selected_tag)
    if not sessions:
        st.caption("No sessions yet")
    else:
        for s in sessions:
            tags = s.get("tags", [])
            tag_badge = f" [{', '.join(tags)}]" if tags else ""
            label = f"{s['goal'][:35]}{tag_badge}{'...' if len(s['goal']) > 35 else ''}"
            col1, col2 = st.columns([5, 1])
            with col1:
                if st.button(label, key=f"sess_{s['id']}", use_container_width=True):
                    full = store.get_session(s["id"])
                    if full:
                        sid = s["id"]
                        if sid not in st.session_state.sessions:
                            st.session_state.sessions[sid] = {
                                "messages": [
                                    {"role": "user", "content": full["goal"]},
                                    {"role": "assistant", "content": full["final_answer"], "result": full},
                                ],
                                "agent": None,
                                "memory": None,
                            }
                        st.session_state.session_id = sid
                        st.rerun()
            with col2:
                if st.button("x", key=f"del_{s['id']}"):
                    store.delete_session(s["id"])
                    if s["id"] in st.session_state.sessions:
                        del st.session_state.sessions[s["id"]]
                    st.rerun()

    st.divider()

    # --- Session Tags ---
    sid = st.session_state.get("session_id")
    if sid:
        with st.expander("Session Tags", expanded=False):
            current_tags = store.get_session(sid)
            current_tags = current_tags.get("tags", []) if current_tags else []
            all_tags = store.get_all_tags(user=st.session_state.username)
            with st.form("tags_form"):
                new_tag = st.text_input("Add tag", placeholder="e.g. research, coding")
                if st.form_submit_button("Add Tag"):
                    if new_tag and new_tag not in current_tags:
                        current_tags.append(new_tag)
                        store.update_tags(sid, current_tags)
                        st.rerun()
            if current_tags:
                for tag in current_tags:
                    col1, col2 = st.columns([3, 1])
                    with col1:
                        st.caption(tag)
                    with col2:
                        if st.button("x", key=f"rm_tag_{tag}"):
                            current_tags.remove(tag)
                            store.update_tags(sid, current_tags)
                            st.rerun()

    st.divider()

    # --- User Profile ---
    with st.expander("Your Profile", expanded=False):
        profile = get_profile(st.session_state.username)
        with st.form("profile_form"):
            name = st.text_input("Name", value=profile.get("name", ""))
            role = st.text_input("Role", value=profile.get("role", ""), placeholder="e.g. Software Engineer, Student")
            interests_str = st.text_input(
                "Research Interests",
                value=", ".join(profile.get("research_interests", [])),
                placeholder="e.g. AI, economics, climate",
            )
            detail = st.selectbox(
                "Detail Level",
                ["concise", "balanced", "detailed"],
                index=["concise", "balanced", "detailed"].index(
                    profile.get("preferences", {}).get("detail_level", "balanced")
                ),
            )
            fmt = st.selectbox(
                "Output Format",
                ["markdown", "plain text", "bullet points"],
                index=["markdown", "plain text", "bullet points"].index(
                    profile.get("preferences", {}).get("output_format", "markdown")
                ),
            )
            if st.form_submit_button("Save Profile"):
                interests = [i.strip() for i in interests_str.split(",") if i.strip()]
                update_profile(st.session_state.username, {
                    "name": name,
                    "role": role,
                    "research_interests": interests,
                    "preferences": {
                        "detail_level": detail,
                        "output_format": fmt,
                    },
                })
                st.success("Profile saved")
                st.rerun()

    st.divider()

    if st.button("Logout", use_container_width=True):
        st.session_state.logged_in = False
        st.session_state.username = ""
        st.session_state.sessions = {}
        st.session_state.session_id = None
        st.session_state.active_agent = None
        st.session_state.active_memory = None
        st.rerun()

# ---------------------------------------------------------------------------
# Main chat area
# ---------------------------------------------------------------------------
st.title("Auto Research")

sid = st.session_state.session_id
current_msgs = st.session_state.sessions.get(sid, {}).get("messages", []) if sid else []

# Render existing messages
for i, msg in enumerate(current_msgs):
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if msg.get("result"):
            render_result(msg["result"], key_prefix=f"h{i}_")

# --- File upload in chat area (per-session) ---
if sid:
    if sid not in st.session_state.session_docs:
        st.session_state.session_docs[sid] = []

    with st.expander("Upload files to this session", expanded=False):
        uploaded = st.file_uploader(
            "PDF, TXT, MD, CSV, JSON",
            type=["pdf", "txt", "md", "csv", "json"],
            accept_multiple_files=True,
            key=f"file_upload_{sid}",
        )
        if uploaded:
            for f in uploaded:
                res = upload_and_index(f.name, f.read())
                if res["success"]:
                    st.success(f"{res['filename']}: {res['chunks']} chunks indexed")
                    # Store extracted text for this session's context
                    st.session_state.session_docs[sid].append({
                        "filename": res["filename"],
                        "text": res.get("text", ""),
                    })
                else:
                    st.error(f"{f.name}: {res['message']}")

        # Show uploaded docs for this session
        docs_for_session = st.session_state.session_docs.get(sid, [])
        if docs_for_session:
            st.caption(f"{len(docs_for_session)} file(s) uploaded to this chat:")
            for d in docs_for_session:
                st.text(f"  {d['filename']} ({len(d['text'])} chars)")

# Handle template injection
if "pending_template" in st.session_state:
    template = st.session_state.pop("pending_template")
    st.session_state["pending_prompt"] = template

pending = st.session_state.pop("pending_prompt", None)
prompt = pending or st.chat_input("Ask anything")

if prompt:
    # Create a new session if none active
    if not sid:
        sid = str(__import__("uuid").uuid4())
        st.session_state.session_id = sid
        st.session_state.sessions[sid] = {
            "messages": [],
            "agent": None,
            "memory": None,
        }

    # Add user message to this session
    st.session_state.sessions[sid]["messages"].append({"role": "user", "content": prompt})

    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        status_text = st.empty()
        status_text.text("Thinking...")
        start = time.time()

        sess_data = st.session_state.sessions[sid]

        if sess_data.get("agent") and sess_data.get("memory"):
            agent = sess_data["agent"]
            memory = sess_data["memory"]
            try:
                result = agent.continue_run(memory, prompt, max_steps=10)
                if agent._last_state and "messages" in agent._last_state:
                    memory.set_messages(agent._last_state["messages"])
                memory.set_log(result["log"])
            except Exception as e:
                result = {"success": False, "final_answer": f"Error: {e}", "steps": 0, "log": []}
        elif mode == "Multi-Agent":
            agent = MultiAgent()
            try:
                result = agent.run(prompt, max_rounds=5)
            except Exception as e:
                result = {"success": False, "final_answer": f"Error: {e}", "steps": 0, "log": []}
        else:
            # Streaming single agent
            user_ctx = get_user_context(st.session_state.username)
            # Build doc context from uploaded files in this session
            session_docs = st.session_state.session_docs.get(sid, [])
            doc_ctx = "\n\n".join(
                f"--- Document: {d['filename']} ---\n{d['text'][:3000]}"
                for d in session_docs
            ) if session_docs else ""
            agent = Agent(
                session_id=sid,
                user_context=user_ctx,
                username=st.session_state.username,
                doc_context=doc_ctx,
            )

            thinking_box = st.empty()
            step_box = st.empty()
            log_placeholder = st.container()

            state = {"thinking": "", "log": [], "final_answer": "", "steps": 0}

            eq, thread, exc_holder = run_async_in_thread(
                agent.arun_stream(prompt, max_steps=15)
            )

            while True:
                ev = eq.get(timeout=120)
                if ev is None:
                    break

                if ev["type"] == "thinking":
                    state["thinking"] += ev["content"]
                    thinking_box.markdown(state["thinking"])

                elif ev["type"] == "tool_start":
                    state["thinking"] = ""
                    thinking_box.empty()
                    tool = ev["tool"]
                    inp = ev.get("input", {})
                    step_num = ev["step"]
                    state["steps"] = step_num
                    step_box.caption(f"Step {step_num}: {tool}...")
                    with log_placeholder:
                        st.markdown(f"**Step {step_num} -- {tool}**")
                        if inp:
                            st.code(json.dumps(inp, indent=2), language="json")
                    state["log"].append({
                        "step": step_num, "thought": "",
                        "tool": tool, "input": inp, "output": "",
                    })

                elif ev["type"] == "tool_end":
                    step_num = ev["step"]
                    tool = ev["tool"]
                    output = ev["output"]
                    step_box.caption(f"Step {step_num}: {tool} done")
                    with log_placeholder:
                        st.text(output[:500])
                    for s in reversed(state["log"]):
                        if s["step"] == step_num:
                            s["output"] = output
                            break

                elif ev["type"] == "final_answer":
                    state["final_answer"] = ev["content"]
                    state["steps"] = ev["steps"]

            thread.join(timeout=5)

            if exc_holder[0]:
                state["final_answer"] = f"Error: {exc_holder[0]}"

            thinking_box.empty()
            step_box.empty()

            result = {
                "success": bool(state["final_answer"]),
                "final_answer": state["final_answer"] or "Max steps reached.",
                "steps": state["steps"],
                "log": state["log"],
            }

            # Store agent + memory on this session for follow-ups
            memory = ConversationMemory()
            if agent._last_state and "messages" in agent._last_state:
                memory.set_messages(agent._last_state["messages"])
            memory.set_log(result["log"])
            sess_data["agent"] = agent
            sess_data["memory"] = memory

        elapsed = round(time.time() - start, 2)
        result["time"] = elapsed

        session_id = store.add_session(
            {
                "goal": prompt,
                "success": result.get("success", False),
                "steps": result.get("steps", 0),
                "time": elapsed,
                "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
                "final_answer": result.get("final_answer", ""),
                "log": result.get("log", []),
            },
            user=st.session_state.username,
        )
        # Update session_id if this was a new session
        if sid != session_id:
            old = st.session_state.sessions.pop(sid, {})
            sid = session_id
            st.session_state.session_id = sid
            st.session_state.sessions[sid] = old

        status_text.empty()

        # Show token usage if available
        usage = get_session_usage(sid)
        if usage:
            st.caption(
                f"Tokens: {format_tokens(usage.get('total_input_tokens', 0))} in / "
                f"{format_tokens(usage.get('total_output_tokens', 0))} out | "
                f"Cost: {format_cost(usage.get('total_cost', 0))}"
            )

        st.markdown(result["final_answer"])
        render_result(result, key_prefix=f"new_{sid}_")

    # Add assistant message to this session's chat
    st.session_state.sessions[sid]["messages"].append({
        "role": "assistant",
        "content": result["final_answer"],
        "result": result,
    })

    # Save findings to session memory
    if result.get("success") and result.get("final_answer"):
        try:
            add_session_memory(
                sid,
                result["final_answer"],
                goal=prompt[:100],
            )
        except Exception:
            pass
